# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install dependencies
      run: go mod tidy

    - name: Generate
      run: go generate -v ./...

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

    - name: Generate coverage report
      run: go test -coverprofile=coverage.out ./ast/... ./generator/... ./cmd/...

    - name: Check coverage
      id: coverage
      run: |
        coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo “total_coverage=$coverage” >> $GITHUB_OUTPUT
        echo "Coverage: $coverage%"
      
    - name: Fail if coverage is below threshold
      run: |
        if [ $(echo "$total_coverage < 50" | bc -l) == "1" ]; then
          echo "Coverage ($total_coverage%) is below the threshold (50%)"
          exit 1
        fi
